### ISSUE TITLE
Checkout Flow for Giftcards

### ISSUE THREAD

**Issue by vuongtng** [lafranceinsoumise/woocommerce-smart-coupons-jlm2017#1]
In a giftcard scenario, most customers intend to purchase for someone else instead for themselves. For the checkout flow, usability can be improved by defaulting "Email giftcard to **someone else**" instead of "Email giftcard to **myself**". This will help prevent customer service calls and force buyers to enter recipient information.

**Comment by guilro** [comment]
Hello. This repository is just a copy of https://woocommerce.com/products/smart-coupons/ for using as a composer dependency. If you are looking for support, please buy the original product and contact the authors.
