### ISSUE TITLE
Add coupon 1 click issue at Cart page 

### ISSUE THREAD

**Issue by dmejiasks** [lafranceinsoumise/woocommerce-smart-coupons-jlm2017#2]
Hi there, 

Looks like add coupon 1 click function works only if Im logged in as Admin.. if Im logged out I can see the coupons and even click on them but coupon isn't applied correctly.

What could be the problem?

**Comment by guilro** [comment]
Hello. This repository is just a copy of https://woocommerce.com/products/smart-coupons/ for using as a composer dependency. If you are looking for support, please buy the original product and contact the authors.
